storage:
  dbPath: /data/db
  journal:
    enabled: true
  wiredTiger:
    engineConfig:
      cacheSizeGB: 1
    collectionConfig:
      blockCompressor: zstd
    indexConfig:
      prefixCompression: true

net:
  bindIp: 0.0.0.0
  port: 27018

replication:
  replSetName: mongo-shard-1

sharding:
  clusterRole: shardsvr

security:
  keyFile: /data/key.file
