version: "3.8"

services:
  pd1:
    image: pingcap/pd:v8.5.6
    container_name: pd1
    restart: always
    command:
      - --name=pd1
      - --data-dir=/data/pd
      - --client-urls=http://0.0.0.0:2379
      - --advertise-client-urls=http://10.204.20.131:2379
      - --peer-urls=http://0.0.0.0:2380
      - --advertise-peer-urls=http://10.204.20.131:2380
      - --initial-cluster=pd1=http://10.204.20.131:2380,pd2=http://10.204.20.132:2380,pd3=http://10.204.20.133:2380
    ports:
      - "2379:2379"
      - "2380:2380"
    volumes:
      - ./data/pd:/data/pd

  tikv1:
    image: pingcap/tikv:v8.5.6
    container_name: tikv1
    restart: always
    command:
      - --addr=0.0.0.0:20160
      - --advertise-addr=10.204.20.131:20160
      - --status-addr=0.0.0.0:20180
      - --data-dir=/data/tikv
      - --pd-endpoints=http://10.204.20.131:2379,http://10.204.20.132:2379,http://10.204.20.133:2379
    ports:
      - "20160:20160"
      - "20180:20180"
    volumes:
      - ./data/tikv:/data/tikv

  tidb1:
    image: pingcap/tidb:v8.5.6
    container_name: tidb1
    restart: always
    command:
      - --store=tikv
      - --path=10.204.20.131:2379,10.204.20.132:2379,10.204.20.133:2379
      - --host=0.0.0.0
      - --advertise-address=10.204.20.131
      - --status-host=0.0.0.0 
      - --status-port=10080
    ports:
      - "4000:4000"
      - "10080:10080"
    volumes:
      - ./data/tidb:/data/tidb
