version: '3.8'

services:
  mongo-master-shard-1-b:
    extra_hosts:
      - "gcp-ev2mgo1a-p2:10.203.25.167" #sesuaikan host dan IP shard 1a
      - "gcp-ev2mgo1b-p2:10.203.25.168" #sesuaikan host dan IP shard 1b
    image: percona/percona-server-mongodb:8.0
    container_name: mongo-master-shard-1-b
    ports:
      - "27201:27018"
    command: ["mongod", "--config", "/etc/mongod.conf"]
    volumes:
      - ./mongo-master-shard-1-b/db:/data/db
      - ./mongo-master-shard-1-b/configdb:/data/configdb
      - /mongodb-docker/key.file:/data/key.file:ro
      - /root/docker-compose-shard-1/mongod.conf:/etc/mongod.conf:ro
    networks:
      - mongo-net

networks:
  mongo-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/16
