version: '3.8'

services:
  mongo-master-shard-2-b:
    extra_hosts:
      - "gcp-ev2mgo2a-p2:10.203.25.169" #sesuaikan host dan IP shard 2a
      - "gcp-ev2mgo2b-p2:10.203.25.170" #sesuaikan host dan IP shard 2b
    image: percona/percona-server-mongodb:8.0
    container_name: mongo-master-shard-2-b
    ports:
      - "27201:27018"
    command: ["mongod", "--config", "/etc/mongod.conf"]
    volumes:
      - ./mongo-master-shard-2-b/db:/data/db
      - ./mongo-master-shard-2-b/configdb:/data/configdb
      - /mongodb-docker/key.file:/data/key.file:ro
      - /root/docker-compose-shard-2/mongod.conf:/etc/mongod.conf:ro
    networks:
      - mongo-net

networks:
  mongo-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/16
