storage:
  dbPath: /data/db
#  journal:
#    enabled: true
#  wiredTiger:
#    engineConfig:
#      cacheSizeGB: 1
#    collectionConfig:
#      blockCompressor: zstd
#    indexConfig:
#      prefixCompression: true

net:
  bindIp: 0.0.0.0
  port: 27019

replication:
  replSetName: mongo-master-config

sharding:
  clusterRole: configsvr

security:
  keyFile: /data/key.file
