services:
  chproxy:
    image: contentsquareplatform/chproxy:v1.30.0
    container_name: ch-proxy
    restart: unless-stopped
    ports:
      - "8124:80"
    volumes:
      - ./config:/opt
    command:
      - "-config=/opt/config.yml"
    environment:
      USERNAME_PROXY: "db_admin"
      PASSWORD_PROXY: "pass_db_admin"
      USERNAME_NODES: "db_admin"
      PASSWORD_NODES: "pass_db_admin"
