services:
  ch-proxy-ecollv3:
    image: tacyuuhon/clickhouse-chproxy
    # image: contentsquareplatform/chproxy:v1.26.4
    container_name: ch-proxy-ecollv3
    ports:
      - "9080:80"
    volumes:
      - ./config/ch-proxy-config.yml:/opt/config.yml
